# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.2
language: objective-c
xcode_project: _Pods.xcodeproj # path to your xcodeproj folder
xcode_scheme: DGNotifyView
# cache: cocoapods
podfile: Example/Podfile
# before_install:
 - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/DGNotifyView.xcworkspace -scheme DGNotifyView-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
